version: '3.9'

services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./public-html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=ctisproj
      - MYSQL_USER=ctisproj
      - MYSQL_PASSWORD=b20Pp7U0xv

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ctisproj
      MYSQL_USER: ctisproj
      MYSQL_PASSWORD: b20Pp7U0xv
    ports:
      - "3306:3306"

volumes:
  mysql_data:

