name: Deploy Docker Compose to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image
      - name: Build and push web service
        id: build-web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctis256_project:latest
        env:
          DOCKER_BUILDKIT: 1

      # Step 5: Verify the Docker image locally
      - name: Verify web service image locally
        run: |
          echo "Verifying the web service image locally..."
          docker images ${{ secrets.DOCKER_HUB_USERNAME }}/ctis256_project:latest

      # Step 6: Verify the Docker image on Docker Hub
      - name: Verify web service image on Docker Hub
        run: |
          echo "Verifying the web service image on Docker Hub..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ctis256_project:latest
          docker images ${{ secrets.DOCKER_HUB_USERNAME }}/ctis256_project:latest

      # Step 7: Install Deno
      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo "export DENO_INSTALL=\"$HOME/.deno\"" >> $GITHUB_ENV
          echo "export PATH=\"$HOME/.deno/bin:\$PATH\"" >> $GITHUB_ENV

      # Step 8: Install Git (ensure git is available)
      - name: Install Git
        run: sudo apt-get install -y git

      # Step 9: Clone the Render CLI repository and install dependencies
      - name: Clone Render CLI repository
        run: |
          source $GITHUB_ENV  # Load Deno environment variables
          git clone https://github.com/render-oss/render-cli.git
          cd render-cli
          make deps

      # Step 10: Initialize Render CLI configuration
      - name: Initialize Render CLI Configuration
        run: |
          mkdir -p ~/.config/render
          echo "{\"apiKey\": \"$RENDER_API_KEY\"}" > ~/.config/render/config.json

      # Step 11: Deploy to Render
      - name: Deploy to Render
        run: |
          ~/.deno/bin/deno run --allow-read --allow-env --allow-run --allow-net https://deno.land/x/render-cli@latest/cli.ts services deploy ctis256_project --env production --dockerfile ./Dockerfile
