name: Deploy Docker Compose to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push web service
        id: build-web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Verify web service image locally
        run: |
          echo "Verifying the web service image locally..."
          docker images ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest

      - name: Verify web service image on Docker Hub
        run: |
          echo "Verifying the web service image on Docker Hub..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest
          docker images ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest

      - name: Build and push MySQL service
        run: |
          docker pull mysql:8.0
          docker tag mysql:8.0 ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0

      - name: Verify MySQL service image locally
        run: docker images ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git golang-go make
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "export DENO_INSTALL=\"$HOME/.deno\"" >> $GITHUB_ENV
          echo "export PATH=\"$HOME/.deno/bin:\$PATH\"" >> $GITHUB_ENV

      - name: Set up Deno environment
        run: |
          echo "DENO_INSTALL=$HOME/.deno" >> $GITHUB_ENV
          echo "PATH=$HOME/.deno/bin:$PATH" >> $GITHUB_ENV

      - name: Clone Render CLI repository
        run: |
          git clone https://github.com/render-oss/render-cli.git
          cd render-cli
          source $GITHUB_ENV
          make deps

      - name: Initialize Render CLI Configuration
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          mkdir -p ~/.config/render
          echo "{\"apiKey\": \"$RENDER_API_KEY\"}" > ~/.config/render/config.json

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          source $GITHUB_ENV
          cd render-cli
          deno task run deploy --service-name ctis256_project
