name: Deploy Docker Compose to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push web service
        id: build-web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/ctis256_project:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Verify web service image locally
        run: |
          echo "Verifying the web service image locally..."
          docker images ${{ env.DOCKER_HUB_USERNAME }}/ctis256_project:latest

      - name: Verify web service image on Docker Hub
        run: |
          echo "Verifying the web service image on Docker Hub..."
          docker pull ${{ env.DOCKER_HUB_USERNAME }}/ctis256_project:latest
          docker images ${{ env.DOCKER_HUB_USERNAME }}/ctis256_project:latest

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "export DENO_INSTALL=\"$HOME/.deno\"" >> $GITHUB_ENV
          echo "export PATH=\"$HOME/.deno/bin:\$PATH\"" >> $GITHUB_ENV

      - name: Clone Render CLI repository
        run: |
          git clone https://github.com/render-oss/render-cli.git
          cd render-cli
          source $GITHUB_ENV  # Load Deno environment variables
          make deps

      - name: Initialize Render CLI Configuration
        run: |
          mkdir -p ~/.config/render
          echo "{\"apiKey\": \"$RENDER_API_KEY\"}" > ~/.config/render/config.json

      - name: Deploy to Render
        run: |
          render services deploy ctis256_project --env production --dockerfile ./Dockerfile
