name: Deploy Docker Compose to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push web service
      id: build-web
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest
      env:
        DOCKER_BUILDKIT: 1

    - name: Verify web service image locally
      run: |
        echo "Verifying the web service image locally..."
        docker images ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest

    - name: Verify web service image on Docker Hub
      run: |
        echo "Verifying the web service image on Docker Hub..."
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest
        docker images ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest

    - name: Build and push MySQL service
      run: |
        docker pull mysql:8.0
        docker tag mysql:8.0 ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0

    - name: Verify MySQL service image locally
      run: docker images ${{ secrets.DOCKER_HUB_USERNAME }}/mysql:8.0

    - name: Log in to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Tag and push web service to Heroku
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        echo "Tagging the web service image for Heroku..."
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/php-web-app:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        echo "Pushing the tagged image to Heroku Container Registry..."
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Verify image pushed to Heroku
      run: |
        echo "Verifying if the image was pushed to Heroku Container Registry..."
        docker pull registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Release web service on Heroku
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
